# Generated by Django 4.1.5 on 2023-01-29 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_room', '0002_alter_trainingblock_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingblock',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
