# Generated by Django 4.1.5 on 2023-01-29 08:30

from django.conf import settings
import django.contrib.auth.base_user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_room', '0006_alter_trainingblock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingblock',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.base_user.AbstractBaseUser.natural_key, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
