# Generated by Django 4.1.5 on 2023-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_room", "0009_alter_trainingblock_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingblock",
            name="duration",
            field=models.IntegerField(default=10),
        ),
    ]
