# Generated by Django 4.1.5 on 2023-01-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_room", "0012_trainingblock_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingblock",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
